# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-05 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosia_adidy', models.CharField(max_length=25, unique=True)),
                ('daty_adidy_1', models.DateField()),
                ('daty_adidy_2', models.DateField(blank=True, null=True)),
                ('vola_adidy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kitapo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosia_kitapo', models.CharField(max_length=25, unique=True)),
                ('daty_kitapo_1', models.DateField()),
                ('daty_kitapo_2', models.DateField(blank=True, null=True)),
                ('vola_vina', models.IntegerField(blank=True, default=0, null=True)),
                ('vola_kitapo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mpandray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kody_mpandray', models.CharField(max_length=6, unique=True)),
                ('anarana_mpandray', models.CharField(max_length=50)),
                ('fanampiny_mpandray', models.CharField(max_length=50)),
                ('finday_mpandray', models.CharField(blank=True, max_length=25, null=True)),
                ('mailaka_mpandray', models.EmailField(blank=True, max_length=254, null=True)),
                ('daty_nandraisana', models.DateField(blank=True, null=True)),
                ('sary_mpandray', models.ImageField(blank=True, null=True, upload_to='photos/user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mpikambana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toerana_mpikambana', models.CharField(max_length=25, unique=True)),
                ('daty_nahampikambana', models.DateField(blank=True, null=True)),
                ('mpandray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Mpandray')),
            ],
        ),
        migrations.CreateModel(
            name='Tossaafi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana_tossaafi', models.CharField(max_length=75, unique=True)),
                ('daty_nipoirany', models.DateField(blank=True, null=True)),
                ('mpandray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Mpandray')),
                ('toerana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Mpikambana')),
            ],
        ),
        migrations.AddField(
            model_name='kitapo',
            name='mpandray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Mpandray'),
        ),
        migrations.AddField(
            model_name='adidy',
            name='mpandray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Mpandray'),
        ),
    ]
