# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-05 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpikambana',
            name='mpandray',
        ),
    ]
