# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0003_auto_20200305_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='tossaafi',
            name='kody_tossaafi',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
