# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0005_remove_tossaafi_kody_tossaafi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tossaafi',
            name='anarana_tossaafi',
        ),
        migrations.RemoveField(
            model_name='tossaafi',
            name='daty_nipoirany',
        ),
        migrations.AddField(
            model_name='tossaafi',
            name='kody_tossaafi',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
