# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0006_auto_20200305_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tossaafi',
            name='anarana_tossaafi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tossaafi',
            name='daty_nipoirany',
            field=models.DateField(blank=True, null=True),
        ),
    ]
