# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0007_auto_20200305_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toerana',
            name='anarana_toerana',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
