# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0009_auto_20200306_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitapo',
            name='totaly_vola',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
