# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0010_kitapo_totaly_vola'),
    ]

    operations = [
        migrations.AddField(
            model_name='adidy',
            name='totaly_adidy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
