# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0011_adidy_totaly_adidy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laminasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daty_laminasa', models.DateTimeField()),
                ('asa', models.CharField(max_length=250)),
                ('toerana', models.CharField(blank=True, max_length=150, null=True)),
                ('tossaafi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Tossaafi')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='laminasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Laminasa'),
        ),
    ]
