# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0013_auto_20200310_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminasa',
            name='daty_laminasa',
            field=models.DateTimeField(),
        ),
    ]
