# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0014_auto_20200310_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tossaafi',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
