# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-12 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etvf', '0016_mpandray_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kristiana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kody_krisitana', models.CharField(max_length=6, unique=True)),
                ('anarana_krisitana', models.CharField(max_length=50)),
                ('fanampiny_krisitana', models.CharField(max_length=50)),
                ('finday_krisitana', models.CharField(blank=True, max_length=25, null=True)),
                ('mailaka_krisitana', models.EmailField(blank=True, max_length=254, null=True)),
                ('daty_nandraisana', models.DateField(blank=True, null=True)),
                ('sary_krisitana', models.ImageField(blank=True, null=True, upload_to='photos/user')),
                ('vola_vina', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('krisitana', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adidy',
            name='mpandray',
        ),
        migrations.RemoveField(
            model_name='kitapo',
            name='mpandray',
        ),
        migrations.RemoveField(
            model_name='mpandray',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mpikambana',
            name='mpandray',
        ),
        migrations.RemoveField(
            model_name='mpikambana',
            name='toerana',
        ),
        migrations.RemoveField(
            model_name='mpikambana',
            name='tossaafi',
        ),
        migrations.DeleteModel(
            name='Adidy',
        ),
        migrations.DeleteModel(
            name='Kitapo',
        ),
        migrations.DeleteModel(
            name='Mpandray',
        ),
        migrations.DeleteModel(
            name='Mpikambana',
        ),
    ]
