# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0017_auto_20200312_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosia_adidy', models.CharField(max_length=25, unique=True)),
                ('daty_adidy_1', models.DateField()),
                ('daty_adidy_2', models.DateField(blank=True, null=True)),
                ('vola_adidy', models.IntegerField(default=0)),
                ('totaly_adidy', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitapo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosia_kitapo', models.CharField(max_length=25, unique=True)),
                ('daty_kitapo_1', models.DateField()),
                ('daty_kitapo_2', models.DateField(blank=True, null=True)),
                ('vola_kitapo', models.IntegerField(default=0)),
                ('totaly_vola', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mpikambana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daty_nahampikambana', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='anarana_krisitana',
            new_name='anarana_kristiana',
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='fanampiny_krisitana',
            new_name='fanampiny_kristiana',
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='finday_krisitana',
            new_name='finday_kristiana',
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='kody_krisitana',
            new_name='kody_kristiana',
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='mailaka_krisitana',
            new_name='mailaka_kristiana',
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='krisitana',
            new_name='mpandray',
        ),
        migrations.RenameField(
            model_name='kristiana',
            old_name='sary_krisitana',
            new_name='sary_kristiana',
        ),
        migrations.AddField(
            model_name='mpikambana',
            name='kristiana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Kristiana'),
        ),
        migrations.AddField(
            model_name='mpikambana',
            name='toerana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Toerana'),
        ),
        migrations.AddField(
            model_name='mpikambana',
            name='tossaafi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Tossaafi'),
        ),
        migrations.AddField(
            model_name='kitapo',
            name='kristiana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Kristiana'),
        ),
        migrations.AddField(
            model_name='adidy',
            name='kristiana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Kristiana'),
        ),
    ]
