# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0020_kristiana_maty'),
    ]

    operations = [
        migrations.AddField(
            model_name='kristiana',
            name='asa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
