# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-13 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0023_adidy_daty_nandoavana_adidy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitapo',
            old_name='daty_nadoavana_kitapo',
            new_name='daty_nandoavana_kitapo',
        ),
    ]
