# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0024_auto_20200313_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='adidy',
            name='toby_faharoa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='adidy',
            name='toby_voalohany',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kitapo',
            name='toby_faharoa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kitapo',
            name='toby_voalohany',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
