# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-17 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0025_auto_20200313_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamaky_boky', models.BooleanField()),
            ],
        ),
    ]
