# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etvf', '0026_sondage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='kristiana',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etvf.Kristiana'),
        ),
        migrations.AddField(
            model_name='sondage',
            name='mahay_mivavaka',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
